name: Build DongTai Core Package and push to Ali OSS

on:
  release:
    types: [ created, edited ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          python-version: 3.7

      - id: release
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          ID=`echo ${TAG_NAME##v}`
          echo "::set-output name=VERSION::$ID"

      - name: Generate version file
        run: |
          cd ${{ github.workspace }} && \
          echo "${{ github.event.repository.name }},version,${{ steps.release.outputs.VERSION }}" >> version.txt && \
          echo "${{ github.event.repository.name }},commit_hash,${GITHUB_SHA}" >> version.txt \

      - name: Replace setup cfg
        run: |
          git config --global user.name 'exexute'
          git config --global user.email '1528360120@qq.com'
          git checkout -b "release-${{ steps.release.outputs.VERSION }}"
          sed -i -e 's/version = .*$/version = ${{ steps.release.outputs.VERSION }}/g' setup.cfg
          cat setup.cfg
          git add .
          git commit -m "Update: change version to $NEW_VERSION"
          git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:"release-$NEW_VERSION"

      - name: Build DongTai Core Package
        run: |
          python setup.py sdist
          
      - uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: "oss-cn-beijing.aliyuncs.com"
          access-key-id: ${{ secrets.OSS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_KEY_SECRET }}
      
      - name: Upload to oss
        run: |
          ossutil cp -rf ./dist/dongtai-${{ steps.get_release_version.outputs.VERSION }}.tar.gz oss://huoqi-public/iast/dongtai-${{ steps.get_release_version.outputs.VERSION }}.tar.gz --meta x-oss-object-acl:public-read
          ossutil cp -rf ./dist/dongtai-${{ steps.get_release_version.outputs.VERSION }}.tar.gz oss://huoqi-public/iast/dongtai-latest.tar.gz --meta x-oss-object-acl:public-read
